export const strings = {
	USERNAME: "username",
	PASSWORD: 'password',
	TOTAL: 'total',
	ADD: "purchases",
	ADDER: "add",
	CANCEL: "cancel",
	OPEN: "open",
	CLOSE: "close",
	EDIT: 'edit',
	SHOW_DATA: "show data",
	MONTHLY: "monthly",
	DAILY: "daily",
	WEEKLY: "weekly",
	HOURLY: "hourly",
	ITEM: "item",
	COST: "cost",
	TYPE: "type",
	SAVE: "save",
	DELETE: "delete",
	LOGOUT: "logout",
	LOGIN: "login"
}